name: curly

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - APP_ENV=${APP_ENV}
      - DB_DATABASE=${DB_DATABASE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=27017
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "${DB_PORT}:27017"
    volumes:
      - mongo_volume:/data/db

volumes:
  mongo_volume:
